Fix the library import issue
The existing version of code will lead to the following runtime error when the credential requires authentication. Adding this line of import should fix this issue. 

```
    auth_req = google.auth.transport.requests.Request()  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google.auth.transport' has no attribute 'requests'. Did you mean: 'Request'?
```