fix: Expand VersionedUnionType tuple in SchemaUnion definition
Fixes ImportError caused by passing a tuple to Union[]. The previous
commit (e290f46) changed VersionedUnionType from a Union type to a
tuple for isinstance checks, but SchemaUnion was still trying to use
it as a Union argument. This expands the tuple elements individually
for Python 3.10+ (UnionType + _UnionGenericAlias) and Python < 3.10
(_UnionGenericAlias only).

Error: TypeError: Union[arg, ...]: each arg must be a type. Got
(<class 'types.UnionType'>, <class 'typing._UnionGenericAlias'>).